footprint: [[0.25, 0.25], [-0.25, 0.25], [-0.25, -0.25], [0.25, -0.25]]
footprint_padding: 0.02

robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 5.0
transform_tolerance: 0.5

resolution: 0.05# 0.1

obstacle_range: 4.5
raytrace_range: 5.0

lethal_cost_threshold: 100

static:
    map_topic: /map
    subscribe_to_updates: true

inflation:
    inflation_radius: 0.35
    #cost_scaling_factor: 5.0

inflation_global:
    inflation_radius: 0.2
    #cost_scaling_factor: 5.0




obstacles_laser:
    observation_sources: laser #camera
    laser: {sensor_frame: laser_link, data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}
    #camera: {sensor_frame: kinect2_link, data_type: PointCloud2, clearing: true, marking: true, topic: kinect2/qhd/points, inf_is_valid: true}

obstacles_voxel:
    observation_sources: camera laser
    camera: {sensor_frame: kinect2_link, data_type: PointCloud2, clearing: true, marking: true, topic: kinect2/qhd/points, inf_is_valid: true, min_obstacle_height: 0.25}
    #origin_z: 0.0
    #z_resolution: 0.05
    #z_voxels: 10 #The number of voxels to in each vertical column, the height of the grid is z_resolution * z_voxels. 
    #publish_voxel_map: true


    


